source: "."
encoding: UTF-8

title: "DevOps Factors: Methodology for building proper DevOps culture"
description: >
  12 patterns for DevOps culture - about priorities, communication, automation, the structure of the team,
  sharing experience, monitoring mechanisms, Continious Integration, etc.

collections:
  factors:
    output: true

sass:
  sass_dir: _sass
  style: compressed